import { pki } from 'node-forge';
export interface KeyAndCert {
    privateKey: pki.rsa.PrivateKey;
    certificate: pki.Certificate;
}
export declare class Ca {
    #private;
    constructor(privateKeyPemFile: string, certPemFile: string);
    generateServerCertificates(hosts: string | string[]): KeyAndCert;
    static RootSubject: ({
        name: string;
        value: string;
        shortName?: undefined;
    } | {
        shortName: string;
        value: string;
        name?: undefined;
    })[];
    static RootExtentions: ({
        name: string;
        cA: boolean;
        keyCertSign?: undefined;
        digitalSignature?: undefined;
        nonRepudiation?: undefined;
        keyEncipherment?: undefined;
        dataEncipherment?: undefined;
        serverAuth?: undefined;
        clientAuth?: undefined;
        codeSigning?: undefined;
        emailProtection?: undefined;
        timeStamping?: undefined;
        client?: undefined;
        server?: undefined;
        email?: undefined;
        objsign?: undefined;
        sslCA?: undefined;
        emailCA?: undefined;
        objCA?: undefined;
    } | {
        name: string;
        keyCertSign: boolean;
        digitalSignature: boolean;
        nonRepudiation: boolean;
        keyEncipherment: boolean;
        dataEncipherment: boolean;
        cA?: undefined;
        serverAuth?: undefined;
        clientAuth?: undefined;
        codeSigning?: undefined;
        emailProtection?: undefined;
        timeStamping?: undefined;
        client?: undefined;
        server?: undefined;
        email?: undefined;
        objsign?: undefined;
        sslCA?: undefined;
        emailCA?: undefined;
        objCA?: undefined;
    } | {
        name: string;
        serverAuth: boolean;
        clientAuth: boolean;
        codeSigning: boolean;
        emailProtection: boolean;
        timeStamping: boolean;
        cA?: undefined;
        keyCertSign?: undefined;
        digitalSignature?: undefined;
        nonRepudiation?: undefined;
        keyEncipherment?: undefined;
        dataEncipherment?: undefined;
        client?: undefined;
        server?: undefined;
        email?: undefined;
        objsign?: undefined;
        sslCA?: undefined;
        emailCA?: undefined;
        objCA?: undefined;
    } | {
        name: string;
        client: boolean;
        server: boolean;
        email: boolean;
        objsign: boolean;
        sslCA: boolean;
        emailCA: boolean;
        objCA: boolean;
        cA?: undefined;
        keyCertSign?: undefined;
        digitalSignature?: undefined;
        nonRepudiation?: undefined;
        keyEncipherment?: undefined;
        dataEncipherment?: undefined;
        serverAuth?: undefined;
        clientAuth?: undefined;
        codeSigning?: undefined;
        emailProtection?: undefined;
        timeStamping?: undefined;
    } | {
        name: string;
        cA?: undefined;
        keyCertSign?: undefined;
        digitalSignature?: undefined;
        nonRepudiation?: undefined;
        keyEncipherment?: undefined;
        dataEncipherment?: undefined;
        serverAuth?: undefined;
        clientAuth?: undefined;
        codeSigning?: undefined;
        emailProtection?: undefined;
        timeStamping?: undefined;
        client?: undefined;
        server?: undefined;
        email?: undefined;
        objsign?: undefined;
        sslCA?: undefined;
        emailCA?: undefined;
        objCA?: undefined;
    })[];
    static ServerSubject: ({
        name: string;
        value: string;
        shortName?: undefined;
    } | {
        shortName: string;
        value: string;
        name?: undefined;
    })[];
    static ServerExtensions: ({
        name: string;
        cA: boolean;
        keyCertSign?: undefined;
        digitalSignature?: undefined;
        nonRepudiation?: undefined;
        keyEncipherment?: undefined;
        dataEncipherment?: undefined;
        serverAuth?: undefined;
        clientAuth?: undefined;
        codeSigning?: undefined;
        emailProtection?: undefined;
        timeStamping?: undefined;
        client?: undefined;
        server?: undefined;
        email?: undefined;
        objsign?: undefined;
        sslCA?: undefined;
        emailCA?: undefined;
        objCA?: undefined;
    } | {
        name: string;
        keyCertSign: boolean;
        digitalSignature: boolean;
        nonRepudiation: boolean;
        keyEncipherment: boolean;
        dataEncipherment: boolean;
        cA?: undefined;
        serverAuth?: undefined;
        clientAuth?: undefined;
        codeSigning?: undefined;
        emailProtection?: undefined;
        timeStamping?: undefined;
        client?: undefined;
        server?: undefined;
        email?: undefined;
        objsign?: undefined;
        sslCA?: undefined;
        emailCA?: undefined;
        objCA?: undefined;
    } | {
        name: string;
        serverAuth: boolean;
        clientAuth: boolean;
        codeSigning: boolean;
        emailProtection: boolean;
        timeStamping: boolean;
        cA?: undefined;
        keyCertSign?: undefined;
        digitalSignature?: undefined;
        nonRepudiation?: undefined;
        keyEncipherment?: undefined;
        dataEncipherment?: undefined;
        client?: undefined;
        server?: undefined;
        email?: undefined;
        objsign?: undefined;
        sslCA?: undefined;
        emailCA?: undefined;
        objCA?: undefined;
    } | {
        name: string;
        client: boolean;
        server: boolean;
        email: boolean;
        objsign: boolean;
        sslCA: boolean;
        emailCA: boolean;
        objCA: boolean;
        cA?: undefined;
        keyCertSign?: undefined;
        digitalSignature?: undefined;
        nonRepudiation?: undefined;
        keyEncipherment?: undefined;
        dataEncipherment?: undefined;
        serverAuth?: undefined;
        clientAuth?: undefined;
        codeSigning?: undefined;
        emailProtection?: undefined;
        timeStamping?: undefined;
    } | {
        name: string;
        cA?: undefined;
        keyCertSign?: undefined;
        digitalSignature?: undefined;
        nonRepudiation?: undefined;
        keyEncipherment?: undefined;
        dataEncipherment?: undefined;
        serverAuth?: undefined;
        clientAuth?: undefined;
        codeSigning?: undefined;
        emailProtection?: undefined;
        timeStamping?: undefined;
        client?: undefined;
        server?: undefined;
        email?: undefined;
        objsign?: undefined;
        sslCA?: undefined;
        emailCA?: undefined;
        objCA?: undefined;
    })[];
    static createRootCertificate(): KeyAndCert;
}
